todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete', views.DeleteView.as_view(), name='delete'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.utils import timezone

class Todo(models.Model):
    title = models.CharField('titel', max_length=200)
    memo = models.TextField('memo')
    deadline = models.DateField()

    def __str__(self):
        return self.title

todo/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'

todo/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from .forms import TodoForm
from .models import Todo

class IndexView(generic.ListView):
    model = Todo
    paginate_by = 5

class DetailView(generic.DetailView):
    model = Todo

class CreateView(generic.CreateView):
    model = Todo
    success_url = reverse_lazy('todo:index')
    form_class = TodoForm

class UpdateView(generic.UpdateView):
    model = Todo
    success_url = reverse_lazy('todo:index')
    form_class = TodoForm

class DeleteView(generic.DeleteView):
    model = Todo
    success_url = reverse_lazy('todo:index')

todo/templates/todo/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Todo List</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">TODO</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home </a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="#">Login </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">Todo List</h1>
            <p class="lead">Todo listを作って毎日を効率的に過ごしましょう。</p>
        </div>

    </div>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

todo/templates/todo/todo_confirm_delete.html
{% extends 'todo/base.html' %}

{% block content %}

<form action="" method="POST">
  <table class="table">
    <tr>
      <th>title</th>
      <td>{{ todo.title }}</td>
    </tr>
    <tr>
      <th>memo</th>
      <td>{{ todo.memo }}</td>
    </tr>
    <tr>
      <th>deadline</th>
      <td>{{ todo.deadline }}</td>
    </tr>

  </table>
<p>こちらのデータを削除します</p>
<button type="submit" class="btn btn-primary">送信</button>
{% csrf_token %}

{% endblock %}

todo/templates/todo/todo_detail.html
{% extends 'todo/base.html' %}

{% block content %}
<table class="table">
  <tr>
    <th>タイトル</th>
    <td>{{ todo.title }}</td>
  </tr>
  <tr>
    <th>本文</th>
    <td>{{ todo.memo | linebreaksbr }}</td>
  </tr>
  <tr>
    <th>締め切り</th>
    <td>{{ todo.deadline }}</td>
  </tr>


</table>

<div class='container'>
  <a href="{% url 'todo:update' todo.pk %}" class="btn btn-success" tabindex="-1" role="button"
        aria-disabled="true">更新</a>
  <a href="{% url 'todo:delete' todo.pk %}" class="btn btn-primary" tabindex="-1" role="button"
        aria-disabled="true">削除</a>
</div>


{% endblock %}

todo/templates/todo/todo_form.html
{% extends 'todo/base.html' %}

{% block content %}

<form action="" method="POST">
  <table class="table">
    <tr>
      <th>title</th>
      <td>{{ form.title }}</td>
    </tr>
    <tr>
      <th>memo</th>
      <td>{{ form.memo }}</td>
    </tr>
    <tr>
      <th>deadline</th>
      <td>{{ form.deadline }}</td>
    </tr>

  </table>

<button type="submit" class="btn btn-primary">送信</button>
{% csrf_token %}

{% endblock %}

todo/templates/todo/todo_list.html
{% extends 'todo/base.html' %}

{% block content %}


<div class='container'>
    <a href="{% url 'todo:create' %}" class="btn btn-info" tabindex="-1" role="button"
     aria-disabled="true">新規作成</a>
</div>

<div class="container">
    {% for item in object_list %}
      <p>{{ item.title }}　期日：{{ item.deadline }}</p>
      <a href="{% url 'todo:update' item.pk %}" class="btn btn-info" tabindex="-1" role="button"
            aria-disabled="true">編集</a>
      <a href="{% url 'todo:delete' item.pk %}" class="btn btn-primary" tabindex="-1" role="button"
            aria-disabled="true">削除</a>
      <a href="{% url 'todo:detail' item.pk %}" class="btn btn-success" tabindex="-1" role="button"
            aria-disabled="true">詳細</a>

    {% endfor %}
  </div>

{% endblock %}